### ISSUE TITLE
Integer overflow in prioriFactor at inheritance levels greater than 5

### ISSUE THREAD

**Issue by michaelfranzl** [DigitalInBlue/Priori#2]
There is an integer overflow in `unsigned int prioriFactor` beginning with the 6th level of inheritance. The value stored at the 6th level is 510510, which requires at least 19 bits, which is greater than the 16 bits required for `unsigned int` by the C++ standard. See https://en.cppreference.com/w/cpp/language/types .

https://github.com/DigitalInBlue/Priori/blob/45b63f27db95f21a4c914b5c6ed3b63a03b835f8/include/priori/priori.h#L80

I am using clang version 13.0.0 on x86_64.

**Comment by DigitalInBlue** [comment]
Thanks for the report.  Fixed!
